### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by einsqing** [python-ffmpegio/python-namedpipe#1]
Traceback (most recent call last):
  File ".\test\pipe.py", line 3, in <module>
    from namedpipe import NPopen
  File "C:\Users\heqing\anaconda3\envs\human-infer\lib\site-packages\namedpipe\__init__.py", line 6, in <module>
    from ._win32 import NPopen
  File "C:\Users\heqing\anaconda3\envs\human-infer\lib\site-packages\namedpipe\_win32.py", line 170, in <module>
    class Win32RawIO(io.RawIOBase):
  File "C:\Users\heqing\anaconda3\envs\human-infer\lib\site-packages\namedpipe\_win32.py", line 210, in Win32RawIO
    def readinto(self, b: WritableBuffer) -> int | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

@tikuma-lsuhsc

**Comment by tikuma-lsuhsc** [comment]
@einsqing - sorry I didn't see your post in a timely manner. But this issue is resolved on v0.1.1. Please note that the minimum Python version has been changed to 3.8.
